import { Link } from 'react-router-dom';
import ProductIcon from './ProductIcon';
import StatusBadge from './StatusBadge';
import { getRelated } from '../data/products';
import { EVENTS, trackProduct } from '../utils/analytics';

/**
 * Cross-product discovery. Relationships are curated per product in
 * products.js (`related`), never generated by category, so unrelated products
 * are not forced together just to fill the row.
 */
export default function RelatedProducts({ product, limit = 3 }) {
  const related = getRelated(product, limit);
  if (related.length === 0) return null;

  return (
    <section aria-labelledby="related-heading" className="border-t border-line/5 pt-12">
      <h2 id="related-heading" className="font-display text-2xl font-bold text-strong">
        You may also like
      </h2>
      <p className="mt-2 text-sm text-text-secondary">
        Related products I build and maintain. Each one stands on its own.
      </p>

      {/* Column count follows the number of items so a short list does not
          leave an obviously empty third of the row. */}
      <ul
        className={`mt-6 grid list-none grid-cols-1 gap-4 sm:grid-cols-2 ${
          related.length >= 3 ? 'lg:grid-cols-3' : ''
        }`}
      >
        {related.map((r) => {
          const to = r.hasDetailPage ? `/products/${r.slug}` : null;

          const inner = (
            <>
              <ProductIcon product={r} size={44} />
              <span className="min-w-0 flex-1">
                <span className="block truncate font-display font-bold text-strong">{r.name}</span>
                <span className="mt-0.5 line-clamp-2 block text-xs leading-relaxed text-text-secondary">
                  {r.shortDescription}
                </span>
              </span>
            </>
          );

          const classes =
            'flex h-full items-start gap-3 rounded-xl border border-border-dark bg-card-dark/70 p-4 transition-colors hover:border-primary/40 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-primary';

          return (
            <li key={r.slug} className="flex">
              {to ? (
                <Link
                  to={to}
                  className={classes}
                  onClick={() => trackProduct(EVENTS.productOpen, r, { from: product.slug })}
                >
                  {inner}
                </Link>
              ) : (
                <div className={`${classes} hover:border-border-dark`}>
                  {inner}
                  <StatusBadge status={r.status} />
                </div>
              )}
            </li>
          );
        })}
      </ul>
    </section>
  );
}
